export type StartupStatus = "ongoing" | "established"

export interface Startup {
  id: string
  name: string
  status: StartupStatus
  ideaVision: string
  goal: string
  productOverview: string
  guide: string
  lead: string
  teamMembers: string[]
  tags: string[]
  progress?: number // 0-100 for ongoing
  demoUrl?: string // for established
  videoUrl?: string
  posterUrl?: string
  displayMedia?: string[]
  /** Optional public path to a downloadable details file (e.g. `/downloads/startups/<id>.pdf`) */
  detailsPath?: string
  updatedAt: string
}

export const startups: Startup[] = [
  {
    id: "chrysalis-smart-souvenir-series",
    name: "CHRYSALIS – Smart Souvenir Prototype Series 1.0",
    status: "ongoing",
    ideaVision: "To redefine academic souvenirs by blending smart technology, sustainable materials, and thoughtful design into meaningful experiences.",
    goal: "Design and develop a series of smart, eco-conscious souvenir prototypes that reflect institutional values of innovation, sustainability, and craftsmanship.",
    productOverview: "CHRYSALIS is a smart souvenir initiative that integrates embedded technology, sustainable materials, and design thinking. The project transforms academic gifting into an experiential narrative through functional prototypes that are symbolic, sensory, and environmentally responsible.",
    guide: "Ankita Sen",
    lead: "Ankita Sen",
    teamMembers: ["**"],
    tags: ["Smart Souvenirs",
    "Embedded Systems",
    "Sustainability",
    "Product Design",
    "Innovation Lab"],
    progress: 62,
    videoUrl: "/videos/startup-demo-1.mp4",
    posterUrl: "/startups/chrysalis-poster.jpg",
    displayMedia: [
      "/startups/Chrysalis1.png",
      "/startups/Chrysalis2.png",
      "/startups/Chrysalis3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/Ankita Sen_Chrysalis Poster.pptx",
  },
  {
    id: "naac-accreditation-made-simple",
    name: "NAAC Accreditation Made Simple",
    status: "ongoing",
    ideaVision: "To simplify, accelerate, and standardize the NAAC accreditation journey for educational institutions through automation, transparency, and data-driven insights.",
    goal: "Develop a cloud-based SaaS platform that streamlines NAAC data validation, verification, score simulation, and reporting, reducing manual effort and dependency on external consultants.",
    productOverview: "NAAC Accreditation Made Simple is a robust SaaS platform designed to support educational institutions throughout the NAAC accreditation lifecycle. It automates data validation, maps institutional data to NAAC criteria, simulates NAAC scores in real time, and generates comprehensive compliance reports.",
    guide: "Prof. (Dr.) Subhabrata Banerjee",
    lead: "Biswajit Chaki",
    teamMembers: ["***"],
    tags: ["NAAC",
    "Accreditation",
    "EdTech SaaS",
    "Academic Compliance",
    "Institutional Ranking"],
    progress: 50,
    videoUrl: "/videos/startup-demo-2.mp4",
    posterUrl: "/research/smart-agriculture-iot.jpg",
    displayMedia: [
      "/startups/NAAC1.png",
      "/startups/NAAC2.png",
      "/startups/NAAC3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/Biswajit Chaki - NAAC.pptx",
  },
  {
    id: "mba-portal-iem-irf",
    name: "MBA Department Digital Portal Redesign",
    status: "ongoing",
    ideaVision: "To build a modern, intuitive, and engaging digital identity for the MBA Department that clearly communicates academic excellence, industry relevance, and institutional credibility.",
    goal: "Redesign the outdated MBA department website into a user-centric, mobile-first, and scalable portal that improves engagement for students, recruiters, and partners.",
    productOverview: "The MBA Portal is a comprehensive digital platform designed to showcase the department’s programs, faculty, research, industry integration, and student achievements. It serves as a single point of access for prospective students, current learners, recruiters, and stakeholders.",
    guide: "Chirabrata Majumder",
    lead: "Jigisha Basu",
    teamMembers: ["Annesha Gayen", "Anushubha Dhar", "Sreyasree Pal", "Yash Gupta"],
    tags: ["MBA Portal",
    "Website Redesign",
    "UX/UI",
    "Higher Education",
    "Digital Transformation",
    "Academic Branding"],
    demoUrl: "https://example.com/demo/writeright",
    videoUrl: "/videos/research-presentation.mp4",
    posterUrl: "/research/educational-technology-platform.jpg",
    displayMedia: [
      "/startups/mba-portal-iem-irf-display-1.png",
      "/startups/mba-portal-iem-irf-display-2.png",
      "/startups/mba-portal-iem-irf-display-3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/Chirabrata_MBA Portal.pptx",
  },
  {
    id: "iem-brand-store-incubator",
    name: "IEM Brand Store Incubator – Nostalgic Memoirs",
    status: "ongoing",
    ideaVision: "To revive and preserve IEM nostalgia by creating a unified brand store that transforms institutional memories into meaningful, collectible merchandise and experiences.",
    goal: "Establish a first-of-its-kind umbrella memorabilia and brand store that monetizes institutional nostalgia while strengthening alumni, student, and investor engagement.",
    productOverview: "The IEM Brand Store Incubator is a business initiative focused on creating and scaling a centralized memorabilia and merchandise ecosystem. It aims to commercialize nostalgic memoirs and institutional identity through curated products, branding strategies, and a scalable retail model.",
    guide: "Subrata Chattopadhyay",
    lead: "Biswajit Chaki",
    teamMembers: ["*****"],
    tags: [   "Brand Incubator",
    "Retail Strategy",
    "Institutional Branding",
    "Nostalgia Marketing",
    "Investor Pitch",
    "Startup Incubation"],
    demoUrl: "https://example.com/demo/fraudguard",
    videoUrl: "/videos/startup-demo-1.mp4",
    posterUrl: "/startups/iem-brand-store-incubator-poster.png",
    displayMedia: [
      "/startups/Brand_Store_1.png",
      "/startups/Brand_Store_2.png",
      "/startups/Brand_Store_3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/Subrata Chattopadhay_Brand Store Incubator Summary .pptx",
  },

  {
    id: "digital-attendance-tracker",
    name: "Digital Attendance Register",
    status: "ongoing",
    ideaVision: "To create a transparent, accurate, and real-time digital attendance ecosystem that minimizes manual effort while improving academic monitoring and compliance.",
    goal: "Integrate biometric attendance data with a faculty-driven mobile solution to enable instant validation, reconciliation, and reporting of classroom attendance.",
    productOverview: "The Digital Attendance Register is a unified attendance management system that combines biometric inputs with a secure backend and an Android application for faculty. It allows real-time attendance verification during live classroom sessions, ensuring accurate records and streamlined administrative workflows.",
    guide: "Chirabrata Majumder",
    lead: "****",
    teamMembers: ["*****"],
    tags: [    "Digital Attendance",
    "Biometric Integration",
    "Academic Systems",
    "Mobile App",
    "Automation"],
    demoUrl: "https://example.com/demo/fraudguard",
    videoUrl: "/videos/startup-demo-1.mp4",
    posterUrl: "/research/blockchain-supply-chain.jpg",
    displayMedia: [
      "/startups/Attendance-Tracker-1.png",
      "/startups/Attendance-Tracker-2.png",
      "/startups/Attendance-Tracker-3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/Chirabrata - Digital Attendance Tracker.pptx",
  },

  {
    id: "northern-lights-led-driver-optimization", 
    name: "Northern Lights – Energy Efficient LED Driver Optimization",
    status: "ongoing",
    ideaVision: "To improve the efficiency, reliability, and sustainability of LED lighting systems by optimizing LED driver architecture for real-world commercial and residential use.",
    goal: "Analyze and compare constant-current (CC) and constant-voltage (CV) LED drivers and develop an optimized constant-current driver that enhances efficiency, lifespan, and light quality.",
    productOverview: "Northern Lights is a research-driven engineering project focused on evaluating LED driver designs for tube lights. By experimentally comparing CC and CV drivers and developing an optimized CC architecture, the project aims to reduce energy loss, heat generation, flicker, and premature failures in LED lighting systems.",
    guide: "Samaresh Majhee",
    lead: "***",
    teamMembers: ["*****"],
    tags: ["LED Lighting",
    "Energy Efficiency",
    "Power Electronics",
    "Sustainability",
    "Green Technology",
    "Smart Lighting"],
    demoUrl: "https://example.com/demo/fraudguard",
    videoUrl: "/videos/startup-demo-1.mp4",
    posterUrl: "/research/blockchain-supply-chain.jpg",
    displayMedia: [
      "/startups/Northern_Lights_1.png",
      "/startups/Northern_Lights_2.png",
      "/startups/Northern_Lights_3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/Samaresh Majhee_Northern Lights Poster.pptx",
  },

  {
    id: "inhouse-3d-printing-prototyping",
    name: "In-House 3D Printing & Rapid Prototyping Facility",
    status: "ongoing",
    ideaVision: "To revive and preserve IEM nostalgia by creating a unified brand store that transforms institutional memories into meaningful, collectible merchandise and experiences.",
    goal: "Enable users to convert ideas into functional physical prototypes quickly and affordably through an end-to-end in-house 3D printing support system.",
    productOverview: "This project establishes an in-house 3D printing and prototyping facility that supports design consultation, optimized printing, and post-processing. It significantly reduces dependency on external vendors while improving turnaround time, quality, and accessibility.",
    guide: "Ms. Rimjhim",
    lead: "****",
    teamMembers: ["*****"],
    tags: ["3D Printing",
    "Rapid Prototyping",
    "Digital Manufacturing",
    "Product Design",
    "Innovation Lab"],
    demoUrl: "https://example.com/demo/fraudguard",
    videoUrl: "/videos/startup-demo-1.mp4",
    posterUrl: "/research/blockchain-supply-chain.jpg",
    displayMedia: [
      "/startups/3D-Printing1.png",
      "/startups/3D-Printing2.png",
      "/startups/3D-Printing3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/RimJhim_3d Printer.pptx",
  },

   {
    id: "grant-in-aid-project-tracker",
    name: "Grant-in-Aid Project Tracker",
    status: "ongoing",
    ideaVision: "To strengthen the research and innovation ecosystem by enabling transparent, efficient, and data-driven tracking of Grant-in-aid projects through a centralized digital platform.",
    goal: "Develop a cloud-based system that automates progress tracking, document management, reporting, and analytics for Grant-in-aid research projects.",
    productOverview: "The Grant-in-Aid Project Tracker is a robust cloud-based platform designed to manage and monitor research projects funded through Grant-in-aid schemes. It centralizes project data, documents, financial details, timelines, and outcomes while offering advanced search, analytics, and reporting capabilities.",
    guide: "Rajiv Ganguly",
    lead: "****",
    teamMembers: ["*****"],
    tags: ["Grant Management",
    "Research Administration",
    "Project Tracking",
    "Cloud Platform",
    "Academic Research Systems"],
    demoUrl: "https://example.com/demo/fraudguard",
    videoUrl: "/videos/startup-demo-1.mp4",
    posterUrl: "/research/blockchain-supply-chain.jpg",
    displayMedia: [
      "/startups/Grant-in-aid1.png",
      "/startups/Grant-in-aid2.png",
      "/startups/Grant-in-aid3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/Rajiv Ganguly_Grant-in-aid Project Tracker.pptx",
  },

   {
    id: "fall-protector-safety-system",
    name: "Fall Protector – Smart Fall Detection & Prevention System",
    status: "ongoing",
    ideaVision: "To enhance personal safety by detecting accidental falls in real time and enabling rapid assistance, especially for elderly individuals and high-risk environments.",
    goal: "Design a reliable fall detection and alert system that minimizes response time during accidents and helps prevent serious injuries.",
    productOverview: "Fall Protector is a safety-focused solution aimed at detecting sudden falls and abnormal motion patterns using smart sensing and alert mechanisms. The system is intended for use by elderly people, patients, workers, or individuals in environments where fall-related injuries pose a serious risk.",
    guide: "Goutam Saha",
    lead: "****",
    teamMembers: ["*****"],
    tags: ["Fall Detection",
    "Healthcare Technology",
    "Safety Systems",
    "IoT",
    "Assistive Technology"
  ],
    demoUrl: "https://example.com/demo/fraudguard",
    videoUrl: "/videos/startup-demo-1.mp4",
    posterUrl: "/research/blockchain-supply-chain.jpg",
    displayMedia: [
      "/startups/Fall_Protector1.png",
      "/startups/Fall_Protector2.png",
      "/startups/Fall_Protector3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/Goutam Saha_Fall Protector.pptx",
  },

   {
    id: "creaboost-xdc-fl-dapp",
    name: "CREABOOST – Blockchain-Based Incentivized Federated Learning dApp",
    status: "ongoing",
    ideaVision: "To create a fair, privacy-first digital advertising ecosystem that empowers content creators by securely aggregating engagement data and rewarding verified contributions transparently.",
    goal: "Build a decentralized dApp that uses federated learning and blockchain to generate accurate ad preference insights while ensuring creator privacy and fair incentive distribution.",
    productOverview: "CREABOOST is a blockchain-based decentralized application that enables content creators to submit engagement metrics from platforms like YouTube, Facebook, and LinkedIn. Using federated learning, the system aggregates insights without storing personal data and rewards creators through transparent, low-cost blockchain transactions.",
    guide: "Sudip Kumar Palit",
    lead: "****",
    teamMembers: ["*****"],
    tags: [ "Federated Learning",
    "Blockchain",
    "Web3",
    "Creator Economy",
    "Privacy-Preserving AI",
    "Digital Advertising"],
    demoUrl: "https://example.com/demo/fraudguard",
    videoUrl: "/videos/startup-demo-1.mp4",
    posterUrl: "/research/blockchain-supply-chain.jpg",
    displayMedia: [
      "/startups/creaboost-xdc-fl-dapp-display-1.png",
      "/startups/creaboost-xdc-fl-dapp-display-2.png",
      "/startups/creaboost-xdc-fl-dapp-display-3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/Sudip Kumar palit_Creaboost.pptx",
  },

   {
    id: "arbitrader-xdc-trading-bot",
    name: "ARBITRADER – Smart Arbitrage Trading for Stocks & Cryptos",
    status: "ongoing",
    ideaVision: "To empower traders with real-time, automated arbitrage intelligence that helps them capitalize on price differences across markets with speed, clarity, and reduced risk.",
    goal: "Design a high-speed arbitrage system that detects profitable price gaps across stock and crypto exchanges and enables fast, low-cost execution using automation and blockchain technology.",
    productOverview: "ARBITRADER is a smart arbitrage trading solution that continuously scans multiple stock and crypto exchanges to detect real-time price differences. Built on the XDC Network, it delivers actionable arbitrage opportunities and secure execution links, helping traders maximize profits with minimal manual effort.",
    guide: "Sudip Kumar Palit",
    lead: "****",
    teamMembers: ["*****"],
    tags: ["Arbitrage Trading",
    "Blockchain",
    "Crypto",
    "Stock Market",
    "Automated Trading",
    "Web3"],
    demoUrl: "https://example.com/demo/fraudguard",
    videoUrl: "/videos/startup-demo-1.mp4",
    posterUrl: "/research/blockchain-supply-chain.jpg",
    displayMedia: [
      "/startups/arbitrader-xdc-trading-bot-display-1.png",
      "/startups/arbitrader-xdc-trading-bot-display-2.png",
      "/startups/arbitrader-xdc-trading-bot-display-3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/Sudip Kumar Palit_arbitrader.pptx",
  },

   {
    id: "tradesim-ai-trading-simulator",
    name: "Trade Sim – AI-Powered Trading Simulation Platform",
    status: "ongoing",
    ideaVision: "To make financial market learning safe, transparent, and beginner-friendly by combining risk-free trading, real-time data, and explainable AI-driven insights.",
    goal: "Build an interactive trading simulation platform that allows learners to practice trading with virtual money while understanding market behavior and AI-recommended strategies.",
    productOverview: "Trade Sim is a robust, AI-powered trading simulation platform developed at IEM CEDS. It enables users to trade using real-time market data with virtual money, receive AI-backed strategy recommendations, and understand decisions through explainable AI (XAI) visualizations. The platform also supports group trading rooms for teaching, training, and competitions.",
    guide: "Saugata Ghosh",
    lead: "Somenath Kuiry",
    teamMembers: ["*****"],
    tags: ["Trading Simulation",
    "FinTech",
    "Explainable AI",
    "Financial Education",
    "AI in Finance",
    "EdTech"],
    demoUrl: "https://example.com/demo/fraudguard",
    videoUrl: "/videos/startup-demo-1.mp4",
    posterUrl: "/research/blockchain-supply-chain.jpg",
    displayMedia: [
      "/startups/tradesim-ai-trading-simulator-display-1.png",
      "/startups/tradesim-ai-trading-simulator-display-2.png",
      "/startups/tradesim-ai-trading-simulator-display-3.png",
    ],
    updatedAt: new Date().toISOString(),
    detailsPath: "/startups/Saugata Ghosh_Somenath Kuiry_TradeSim.pdf",
  },
]

export function getSummary() {
  const total = startups.length
  const ongoing = startups.filter((s) => s.status === "ongoing").length
  const established = startups.filter((s) => s.status === "established").length
  return { total, ongoing, established }
}
